from selenium.webdriver.common.by import By

class OrderPageLocators:
    NAME = (By.XPATH, "//input[@placeholder = '* Имя']")
    SURNAME = (By.XPATH, "//input[@placeholder = '* Фамилия']")
    ADRESS = (By.XPATH, "//input[@placeholder = '* Адрес: куда привезти заказ']")
    PHONE = (By.XPATH, "//input[@placeholder = '* Телефон: на него позвонит курьер']")
    METRO = (By.XPATH, "//input[@placeholder = '* Станция метро']")
    FARTHER_BUTTON = (By.XPATH, "//button[text() = 'Далее']")
    SELECT_STATION_1 = (By.XPATH, "//div[contains(text(), 'Боровицкая')]")
    SELECT_STATION_2 = (By.XPATH, "//div[contains(text(), 'Черкизовская')]")
    HEADER_BUTTON_ORDER = (By.XPATH, "//button[@class = 'Button_Button__ra12g']")
    DOWN_BUTTON_ORDER = (By.XPATH, "//button[@class = 'Button_Button__ra12g Button_Middle__1CSJM']")
    DATE_ORDER = (By.XPATH, "//input[@placeholder = '* Когда привезти самокат']")
    DAY_ORDER_1 = (By.XPATH, "//div[@aria-label = 'Choose пятница, 3-е мая 2024 г.']")
    DAY_ORDER_2 = (By.XPATH, "//div[@aria-label = 'Choose понедельник, 13-е мая 2024 г.']")
    RENTAL_PERIOD = (By.XPATH, "//div[@class = 'Dropdown-root']")
    RENTAL_PERIOD_1 = (By.XPATH, "//div[@class='Dropdown-option'and text()='четверо суток']")
    RENTAL_PERIOD_2 = (By.XPATH, "//div[@class='Dropdown-option'and text()='сутки']")
    SCOOTER_COLOR_1 = (By.XPATH, "//input[@id= 'black']")
    SCOOTER_COLOR_2 = (By.XPATH, "//input[@id= 'grey']")
    COMMENT_COURIER = (By.XPATH, "//input[@placeholder = 'Комментарий для курьера']")
    APPROVAL_BUTTON = (By.XPATH, "//button[text() = 'Да']")
    ORDER_PLACED = (By.XPATH, "//div[text() = 'Заказ оформлен']")